<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>Laporan Kalibrasi Validator CLIForge</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        h1 { font-size: 22px; margin-bottom: 4px; }
        h2 { font-size: 15px; margin-top: 22px; }
        p { line-height: 1.5; }
        .muted { color: #6b7280; }
        .summary { display: table; width: 100%; margin-top: 16px; }
        .box { display: table-cell; width: 25%; border: 1px solid #d1d5db; padding: 12px; }
        .big { font-size: 26px; font-weight: bold; }
        .eligible { color: #047857; font-weight: bold; }
        .not-eligible { color: #be123c; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #d1d5db; padding: 7px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; font-size: 10px; text-transform: uppercase; }
        .pass { color: #047857; font-weight: bold; }
        .fail { color: #be123c; font-weight: bold; }
        .center { text-align: center; }
        .formula { border: 1px solid #c7d2fe; background: #eef2ff; padding: 12px; margin-top: 12px; }
    </style>
</head>
<body>
    <h1>Laporan Kalibrasi Validator CLIForge</h1>
    <p class="muted">Generated by CLIForge · <?php echo e($generatedAt?->format('d M Y H:i')); ?></p>

    <p>
        Laporan ini memuat perbandingan keputusan assessor manusia dan algoritma state-based validation pada CLIForge.
        Percent Agreement digunakan untuk mengukur tingkat kesesuaian keputusan antara guru dan CLIForge Agent.
    </p>

    <div class="summary">
        <div class="box"><div>Total</div><div class="big"><?php echo e($total); ?></div></div>
        <div class="box"><div>Kesepakatan</div><div class="big"><?php echo e($agreement); ?></div></div>
        <div class="box"><div>Ketidaksepakatan</div><div class="big"><?php echo e($disagreement); ?></div></div>
        <div class="box"><div>Percent Agreement</div><div class="big"><?php echo e(number_format($pa, 2)); ?>%</div></div>
    </div>

    <p style="margin-top: 14px;">
        Status:
        <?php if($isEligible): ?>
            <span class="eligible">Validator Layak Digunakan</span>
        <?php else: ?>
            <span class="not-eligible">Validator Perlu Kalibrasi Ulang</span>
        <?php endif; ?>
    </p>

    <div class="formula">
        <strong>Rumus:</strong><br>
        PA = Jumlah Kesepakatan / (Jumlah Kesepakatan + Jumlah Ketidaksepakatan) × 100%<br>
        PA = <?php echo e($agreement); ?> / (<?php echo e($agreement); ?> + <?php echo e($disagreement); ?>) × 100% = <?php echo e(number_format($pa, 2)); ?>%
    </div>

    <h2>Detail Kalibrasi Rule Validator</h2>

    <table>
        <thead>
            <tr>
                <th>Siswa</th>
                <th>Lab</th>
                <th>Rule</th>
                <th>Guru</th>
                <th>Agent</th>
                <th>Agreement</th>
                <th>Catatan</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $rows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr>
                    <td><?php echo e($row->labResult?->user?->name ?? '-'); ?><br><span class="muted"><?php echo e($row->labResult?->user?->email ?? '-'); ?></span></td>
                    <td><?php echo e($row->labResult?->lab?->title ?? '-'); ?><br><span class="muted">Result #<?php echo e($row->lab_result_id); ?></span></td>
                    <td><?php echo e($row->rule_name); ?></td>
                    <td class="<?php echo e(strtoupper($row->teacher_decision) === 'PASS' ? 'pass' : 'fail'); ?>"><?php echo e(strtoupper($row->teacher_decision)); ?></td>
                    <td class="<?php echo e(strtoupper($row->agent_decision) === 'PASS' ? 'pass' : 'fail'); ?>"><?php echo e(strtoupper($row->agent_decision)); ?></td>
                    <td class="center"><?php echo e($row->is_agreement ? 'Ya' : 'Tidak'); ?></td>
                    <td><?php echo e($row->note ?: '-'); ?></td>
                </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>
</body>
</html>
<?php /**PATH C:\xampp\htdocs\cliforge\resources\views/validator-calibration/report-pdf.blade.php ENDPATH**/ ?>